CREATE TABLE courier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0 INCREMENT BY 1) PRIMARY KEY,
    type VARCHAR(4) NOT NULL
);

CREATE TABLE region (
    id INTEGER PRIMARY KEY
);

CREATE TABLE courier_region (
    courier_id BIGINT,
    region_id INTEGER,
    FOREIGN KEY (courier_id) REFERENCES courier(id),
    FOREIGN KEY (region_id) REFERENCES region(id)
);

CREATE TABLE shift (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0 INCREMENT BY 1) PRIMARY KEY,
    working_hours VARCHAR(11) NOT NULL UNIQUE
);

CREATE TABLE courier_shift (
    courier_id BIGINT,
    shift_id INTEGER,
    FOREIGN KEY (courier_id) REFERENCES courier(id),
    FOREIGN KEY (shift_id) REFERENCES shift(id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0 INCREMENT BY 1) PRIMARY KEY,
    weight FLOAT NOT NULL,
    cost INTEGER NOT NULL,
    completed_time TIMESTAMP,
    courier_id BIGINT,
    region_id INTEGER NOT NULL,
    FOREIGN KEY (courier_id) REFERENCES courier(id),
    FOREIGN KEY (region_id) REFERENCES region(id)
);

CREATE TABLE delivery_time (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0 INCREMENT BY 1) PRIMARY KEY,
    delivery_hours VARCHAR(11) NOT NULL UNIQUE
);

CREATE TABLE order_delivery_time (
    order_id BIGINT,
    delivery_time_id INTEGER,
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (delivery_time_id) REFERENCES delivery_time(id)
);